version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Start with Java 11
    commands:
      - echo "Installing Java 17..."
      - wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      - tar -xzf amazon-corretto-17-x64-linux-jdk.tar.gz -C /opt
      - export JAVA_HOME=/opt/amazon-corretto-17*
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - javac -version
  pre_build:
    commands:
      - echo "Starting build at $(date)"
      - mvn clean
  build:
    commands:
      - echo "Building Spring PetClinic application"
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed at $(date)"
      - cp target/*.jar spring-petclinic.jar
      - mkdir -p scripts
      - cp cicd/scripts/* scripts/ || echo "No scripts to copy"

artifacts:
  files:
    - spring-petclinic.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no
